//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by https://github.com/dleks
//

import Foundation
import RxSwift
import RxRelay
import RxFlow

struct ___VARIABLE_sceneName___ViewModel: Stepper {
    var steps = PublishRelay<Step>()
    
}
