//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by https://github.com/dleks
//

import UIKit
import RxSwift
import RxCocoa
import RxRelay

class ___VARIABLE_sceneName___ViewController: UIViewController {
    
    private let disposeBag = DisposeBag()
    var viewModel: ___VARIABLE_sceneName___ViewModel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        bind()
    }
}

//MARK: Binding
extension ___VARIABLE_sceneName___ViewController {
    func bind() {
          
      }
}
